### ISSUE TITLE
Flex and nulls

### ISSUE THREAD

**Issue by Ian-May** [nealcrook/multicomp6809#1]
Hi Neal - there are at least 2 ways to get rid of the nulls in FLEX. The best is to modify the byte at location $CC05 - TTYSET Null Count. The default is 4 - set it to zero. The second method is to use the "TTYSET" command in your FLEX startup.txt file (or anytime on the command line). TTYSET,NL=0 will set zero nulls. The downside of this method is that it will have already printed some nulls before it gets this far. Cheer, Ian.

**Comment by nealcrook** [comment]
Hi Ian,
thanks for the suggestions. I have now learned how to use FIX and documented a flow for using that to do the patch, which I can see is much neater and faster than the startup file.
Neal.
